In [11]:
import tensorflow as tf
import numpy as np

#### TensorFlow has two main componenats:
    1. Tensors i.e. variables/placeholders
    2. Operations

### 1. Tensors

Constants

In [3]:
a = tf.constant(5,name="a")
b = tf.constant(10,name="b")
print(a)

Tensor("a:0", shape=(), dtype=int32)


There is no value in a & b yet, they are just initiliazed. We have have create a session and excute the session to get a & b

In [5]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    print("a = " + str(sess.run(a)))

a = 5


**Placeholder**

In [7]:
c = tf.placeholder(tf.int32)
with tf.Session() as sess:
    print("square(5) = " + str(sess.run(c*c,feed_dict={c:5})))

square(5) = 25


### 2. Operations

In [10]:
x = tf.multiply(a,b)
with tf.Session() as sess:
    print("5 * 10 = {0}".format(sess.run(x)))

5 * 10 = 50


### This also works on vectorized version

In [21]:
np.random.seed(1)

w = tf.constant(np.random.randn(4,5))
a = tf.constant(np.random.randn(5,3))
b = tf.constant(np.random.randn(4,1))

equ = tf.add(tf.matmul(w,a),b)

with tf.Session() as sess:
    print(sess.run(equ))

[[-3.20668652  1.8005875   1.85639849]
 [ 2.72667484 -1.47769563 -4.14060543]
 [-3.35317619 -0.33868954  2.43892254]
 [ 2.51349321  0.54507437  0.61325128]]
